:memo: Added considerations and future work doc
polyphene/fvm-rs-sdk-docs pull request #7
Opened 2022-08-18 13:38 UTC by tchataigner

This PR introduces documentation for considerations while building the SDK and already identified future work that will need to be conducted.

2022-08-18 15:02 UTC, PhilippeMts requested changes
Thanks for this update @tchataigner .

You'll find a few typos you may fix.

One last comment: the _Get Started_ button on the front page may link to rather link to _Considerations_ instead of _Usage_ which weight is higher in the ToC. 👍

2022-08-18 15:02 UTC, PhilippeMts commented on content/en/docs/reference/considerations.md
> +ran in the FVM.
```suggestion
run in the FVM.
```

2022-08-18 15:02 UTC, PhilippeMts commented on content/en/docs/reference/future-work.md
> +serde/dispatch/etc , code injection at dedicated places in the generated invoke ...) and one implemented.
```suggestion
serde/dispatch/etc., code injection at dedicated places in the generated invoke ...) and one implemented.
```

2022-08-18 15:02 UTC, PhilippeMts commented on content/en/docs/reference/future-work.md
> +> If you have any ideas for iterations that you can not find in the list down below please feel free
```suggestion
> If you have any idea for iterations that you can not find in the list down below please feel free
```

2022-08-18 16:09 UTC, tchataigner commented
> One last comment: the Get Started button on the front page may link to rather link to Considerations instead of Usage which weight is higher in the ToC. 👍

Yes you are right ! Changing that !

2022-08-19 04:59 UTC, PhilippeMts approved these changes

2022-08-19 07:38 UTC, closed without merging